name: Update cached values

on:
  schedule:
    - cron: "* 2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: "Setup Bun"
      uses: oven-sh/setup-bun@v1

    - name: "Run parsers"
      run: |
        git clone https://github.com/Lolikarbuzik/jbtradingvalues.git
        cd jbtradingvalues
        bun install
        bun . "${{ secrets.PRIVATE_KEY }}"

    - name: "Commit changes"
      run: |
        cd jbtradingvalues
        git remote add origin https://Lolikarbuzik:${{ secrets.DEF_NOT_MY_PASS }}@github.com/Lolikarbuzik/jbtradingvalues.git
        git add .
        git commit -m "Automated update"
        git push
