name: Update cached values

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: "Setup Bun"
      uses: oven-sh/setup-bun@v1

    - name: "Run parsers"
      run: |
        bun install
        bun . "${{ secrets.PRIVATE_KEY }}"

    - name: "Commit changes"
      run: |
        git config user.name "Lolikarbuzik"
        git config user.email "${{ secrets.MY_EMAIL }}"
        git add .
        git commit -m "Automated update"
        git push
